[package]
name = "everscale-client-jni"
version = "1.41.0"
authors = ["Igor Vasilev"]
edition = "2018"

[lib]
name = "ton_client_jni"
crate-type = ["cdylib"]

[dependencies]
jni = "0.18.0"
lazy_static = "1.1.0"
parking_lot = "0.11"
ton_client = { path = "../target/TON-SDK/ton_client" }


